apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: customdeployments.controller.crd
spec:
    group: controller.crd
    version: v1beta1
    names:
        kind: CustomDeployment
        plural: customdeployments
    scope: Namespaced
